### ISSUE TITLE
misskey.js not provided

### ISSUE THREAD

**Issue by ThatOneCalculator** [fruitriin/missRirica-client#26]
Running `yarn install` gives:

```
[1/4] Resolving packages...
error Package "misskey-js" refers to a non-existing file '"/home/kainoa/Git/misskey.js"'.
```

and `package.json` has the line

```
"misskey-js": "../misskey.js",
```

instead of the NPM dependency. Is there any reason why this is, and why isn't the correct dependency bundled?

**Comment by SeolHa314** [comment]
Since misskey.js on npm has not been updated for misskey v13, you need to provide your own build of misskey.js.
https://github.com/misskey-dev/misskey.js/issues/53

**Comment by fruitriin** [comment]
how to build note:

- yarn add misskey-js from github
- cd node_modules/misskey-js
- npm install
- npx tsc

if it isn't enough, anytime give me comment

**Comment by fruitriin** [comment]
1.5.2 will depends replace miskey-js with yamisskey-js
